tbd# project.yml
# ... (other parts of your project.yml)
        environment:
          #TARGET_API_URL: "https://api.openweathermap.org/data/2.5/onecall?lat=34.05&lon=-118.25&exclude=minutely,daily&appid={your_open_weather_api_key}" # Replace with actual API & your key
          SENDER_EMAIL: "jpf.test.81@gmail.com"
          SENDER_EMAIL_PASSWORD: "mxzvlexszizktngq" # <<< USE THIS GENERATED PASSWORD
          RECEIVER_EMAIL: "jorgefpont@gmail.com"
          SMTP_SERVER: "smtp.gmail.com"
          SMTP_PORT: "587"
# ... (rest of project.yml)
