# Digital Ocean Functions project.yml
packages:
  - name: weather-info-app
    environment:
      TARGET_API_URL: "https://api.openweathermap.org/data/3.0/onecall"
      TARGET_API_KEY: "a83c5b4eede4d997dc83a9105c152aa4"
      
      # location data
      # Menlo Park, California
      LATTITUDE: "37.433"
      LONGITUDE: "-122.207"
      PLACE: "Menlo Park, CA"
      LOC_TIMEZONE: "US/Pacific"
    
      SENDER_EMAIL: "jpf.test.81@gmail.com"
      SENDER_PASSWORD: "crwqgtfxihtviutn"
      RECEIVER_EMAIL: "jorgefpont@gmail.com"
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "587"
    functions:
      - name: __main__
        runtime: python:3.9
        web: true
        annotations:
          # Schedule the function to run every hour
          schedule: "0 * * * *"